import { useState } from 'react'
import { HiChevronDown, HiChevronUp, HiPlus, HiTrash } from 'react-icons/hi'
import Card from '../ui/Card/Card'
import Button from '../ui/Button/Button'
import Loader from '../ui/Loader/Loader'
import type { ListaPrecioAdmin, ListaPrecioPayload, ReglaPrecioCantidadBorrador } from '../../services/admin/precioCantidad.api'
import { useAsignarListaPrecio, useConfiguracionPrecioCantidad, useEliminarListaPrecio, useGuardarListaPrecio, usePrevisualizarPrecioCantidad } from '../../hooks/admin/usePreciosCantidadAdmin'

interface Props { idProducto: number }
const reglaNueva = (orden: number): ReglaPrecioCantidadBorrador => ({ nombre: 'Nuevo umbral', cantidadMinima: 1, precioPorPresentacion: '0.00', principal: false, activo: true, orden })
const listaNueva = (): ListaPrecioPayload => ({ nombre: 'Nueva lista', principal: false, activo: true, reglas: [{ ...reglaNueva(0), nombre: 'Precio normal', principal: true, precioPorPresentacion: '0.00' }] })
const errorTexto = (error: unknown) => typeof error === 'object' && error !== null && 'response' in error ? (error as { response?: { data?: { error?: string } } }).response?.data?.error ?? 'No se pudo guardar.' : 'No se pudo guardar.'
const aPayload = (lista: ListaPrecioAdmin): ListaPrecioPayload => ({ nombre: lista.nombre, principal: lista.principal, activo: lista.activo, reglas: lista.reglas.map((regla) => ({ ...regla })) })
const aCentavos = (valor: string) => { const [entero, decimal = ''] = valor.split('.'); return BigInt(entero || '0') * 100n + BigInt((decimal + '00').slice(0, 2)) }

function EditorLista({ inicial, onGuardar, guardando }: { inicial: ListaPrecioPayload; onGuardar: (lista: ListaPrecioPayload) => void; guardando: boolean }) {
  const [lista, setLista] = useState(inicial); const [cantidad, setCantidad] = useState('1'); const preview = usePrevisualizarPrecioCantidad()
  const actualizar = (i: number, cambio: Partial<ReglaPrecioCantidadBorrador>) => setLista((actual) => ({ ...actual, reglas: actual.reglas.map((regla, indice) => indice === i ? { ...regla, ...cambio } : regla) }))
  const marcarPrincipal = (i: number) => setLista((actual) => ({ ...actual, reglas: actual.reglas.map((regla, indice) => ({ ...regla, principal: indice === i, activo: indice === i ? true : regla.activo })) }))
  const advertencias = lista.reglas.filter((r) => r.activo).sort((a,b) => a.cantidadMinima-b.cantidadMinima).flatMap((r,i,arr) => i === 0 ? [] : aCentavos(r.precioPorPresentacion) * BigInt(r.cantidadMinima) < aCentavos(arr[i-1].precioPorPresentacion) * BigInt(r.cantidadMinima - 1) ? [r.cantidadMinima] : [])
  return <div className="mt-4 space-y-3 rounded-lg border border-gray-700 bg-gray-900/40 p-4">
    <div className="grid gap-3 sm:grid-cols-[1fr_auto_auto]"><label className="text-xs text-gray-300">Nombre de lista<input value={lista.nombre} onChange={(e) => setLista({ ...lista, nombre: e.target.value })} className="mt-1 w-full rounded border border-gray-600 bg-gray-700 px-3 py-2 text-white" /></label><label className="inline-flex items-center gap-2 text-xs text-gray-200"><input type="checkbox" checked={lista.principal} onChange={(e) => setLista({ ...lista, principal: e.target.checked, activo: e.target.checked || lista.activo })} /> Lista principal</label><label className="inline-flex items-center gap-2 text-xs text-gray-200"><input type="checkbox" checked={lista.activo} onChange={(e) => setLista({ ...lista, activo: e.target.checked, principal: e.target.checked ? lista.principal : false })} /> Activa</label></div>
    {lista.reglas.map((regla, i) => <div key={regla.idReglaPrecio ?? i} className="grid gap-2 rounded border border-gray-700 p-3 sm:grid-cols-[1fr_110px_140px_auto] sm:items-end"><label className="text-xs text-gray-300">Nombre<input value={regla.nombre} onChange={(e) => actualizar(i,{nombre:e.target.value})} className="mt-1 w-full rounded border border-gray-600 bg-gray-700 px-2 py-1.5 text-white" /></label><label className="text-xs text-gray-300">Desde<input type="number" min="1" value={regla.cantidadMinima} onChange={(e) => actualizar(i,{cantidadMinima:Number(e.target.value)})} className="mt-1 w-full rounded border border-gray-600 bg-gray-700 px-2 py-1.5 text-white" /></label><label className="text-xs text-gray-300">Bs / presentación<input value={regla.precioPorPresentacion} onChange={(e) => actualizar(i,{precioPorPresentacion:e.target.value})} className="mt-1 w-full rounded border border-gray-600 bg-gray-700 px-2 py-1.5 text-white" /></label><div className="flex flex-wrap items-center gap-2"><label className="inline-flex min-h-11 items-center gap-2 text-xs text-gray-300"><input type="radio" checked={regla.principal && regla.activo} onChange={() => marcarPrincipal(i)} /> Principal</label><Button size="icon" variant="danger" aria-label={`Eliminar umbral ${regla.nombre}`} className="min-h-11 min-w-11 sm:h-8 sm:w-8 sm:min-h-0 sm:min-w-0" disabled={lista.reglas.length === 1} onClick={() => setLista({...lista, reglas:lista.reglas.filter((_,x)=>x!==i)})}><HiTrash /></Button></div></div>)}
    <Button size="sm" variant="light" onClick={() => setLista({...lista, reglas:[...lista.reglas,reglaNueva(lista.reglas.length)]})}><HiPlus /> Agregar umbral</Button>
    {advertencias.length > 0 && <p className="text-xs text-amber-300">Advertencia: desde {advertencias.join(', ')}, comprar más presentaciones puede costar menos en total.</p>}
    <div className="border-t border-gray-700 pt-3"><p className="text-xs font-semibold text-gray-200">Vista previa por umbral</p><div className="mt-2 flex items-end gap-2"><label className="text-xs text-gray-300">Presentaciones<input type="number" min="1" value={cantidad} onChange={(e)=>setCantidad(e.target.value)} className="mt-1 block w-28 rounded border border-gray-600 bg-gray-700 px-2 py-1.5 text-white" /></label><Button size="sm" loading={preview.isPending} onClick={() => preview.mutate({cantidad:Number(cantidad),reglas:lista.reglas})}>Calcular</Button></div>{preview.data && <p className="mt-2 text-sm text-primary-light">Desde {preview.data.cantidadMinimaAplicada}: Bs {preview.data.precioPorPresentacion} c/u · Total Bs {preview.data.subtotal}</p>}{preview.error && <p className="mt-2 text-xs text-red-300">{errorTexto(preview.error)}</p>}</div>
    <Button loading={guardando} onClick={() => onGuardar(lista)}>Guardar lista</Button>
  </div>
}

export default function PreciosCantidadEditor({ idProducto }: Props) {
  const config = useConfiguracionPrecioCantidad(idProducto); const guardar = useGuardarListaPrecio(idProducto); const eliminar = useEliminarListaPrecio(idProducto); const asignar = useAsignarListaPrecio(idProducto); const [abierta,setAbierta]=useState<number|null>(null); const [seleccionadas,setSeleccionadas]=useState<number[]>([]); const [listaDestino,setListaDestino]=useState(''); const [mensaje,setMensaje]=useState<string|null>(null)
  if (config.isLoading) return <Loader size="md" showText={false} />
  if (!config.data) return <p className="text-red-300">{errorTexto(config.error)}</p>
  const listas = config.data.listasPrecio
  const guardarLista = (body: ListaPrecioPayload, idListaPrecio?: number) => { setMensaje(null); guardar.mutate({idListaPrecio,body},{onSuccess:()=>setAbierta(null),onError:(e)=>setMensaje(errorTexto(e))}) }
  return <div className="mt-4 space-y-5"><Card variant="admin" padding="md"><h2 className="text-base font-semibold text-gray-100">Listas de precios</h2><p className="mt-1 text-xs text-gray-400">Cada umbral define el precio por presentación desde esa cantidad. La tienda pública seguirá usando precios legacy hasta completar la migración.</p>{mensaje&&<p className="mt-3 text-sm text-red-300">{mensaje}</p>}<div className="mt-4 space-y-3">{listas.map((lista)=><div key={lista.idListaPrecio} className="rounded-lg border border-gray-700 bg-gray-900/30 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-medium text-gray-100">{lista.nombre} {lista.principal&&<span className="ml-2 rounded bg-primary/20 px-2 py-0.5 text-xs text-primary-light">Principal</span>}</p><p className="mt-1 text-xs text-gray-400">{lista.reglas.filter(r=>r.activo).map(r=>`Desde ${r.cantidadMinima}: Bs ${r.precioPorPresentacion}`).join(' · ')}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" className="min-h-11 sm:min-h-0" variant="light" onClick={()=>setAbierta(abierta===lista.idListaPrecio?null:lista.idListaPrecio)}>{abierta===lista.idListaPrecio?<HiChevronUp/>:<HiChevronDown/>}Editar</Button><Button size="icon" variant="danger" aria-label={`Eliminar lista ${lista.nombre}`} className="min-h-11 min-w-11 sm:h-8 sm:w-8 sm:min-h-0 sm:min-w-0" disabled={lista.principal||eliminar.isPending} onClick={()=>eliminar.mutate(lista.idListaPrecio,{onError:(e)=>setMensaje(errorTexto(e))})}><HiTrash /></Button></div></div>{abierta===lista.idListaPrecio&&<EditorLista inicial={aPayload(lista)} guardando={guardar.isPending} onGuardar={(body)=>guardarLista(body,lista.idListaPrecio)} />}</div>)}</div><div className="mt-4">{abierta===0?<EditorLista inicial={listaNueva()} guardando={guardar.isPending} onGuardar={(body)=>guardarLista(body)} />:<Button variant="light" size="sm" className="min-h-11 sm:min-h-0" onClick={()=>setAbierta(0)}><HiPlus/> Nueva lista</Button>}</div></Card>
  <Card variant="admin" padding="md"><h2 className="text-base font-semibold text-gray-100">Asignación de variantes</h2><p className="mt-1 text-xs text-gray-400">Selecciona variantes y asígnales una lista compartida. “Principal” usa la lista principal del producto.</p><div className="mt-3 flex flex-wrap items-end gap-2"><label className="w-full text-xs text-gray-300 sm:w-auto">Aplicar lista<select value={listaDestino} onChange={(e)=>setListaDestino(e.target.value)} className="mt-1 block w-full rounded sm:w-auto border border-gray-600 bg-gray-700 px-2 py-1.5 text-white"><option value="">Principal</option>{listas.filter(l=>l.activo).map(l=><option key={l.idListaPrecio} value={l.idListaPrecio}>{l.nombre}</option>)}</select></label><Button size="sm" disabled={!seleccionadas.length} loading={asignar.isPending} onClick={()=>asignar.mutate({idsVariante:seleccionadas,idListaPrecio:listaDestino?Number(listaDestino):null},{onSuccess:()=>setSeleccionadas([]),onError:(e)=>setMensaje(errorTexto(e))})}>Aplicar a seleccionadas</Button></div><div className="mt-3 divide-y divide-gray-700">{config.data.variantes.map(v=><label key={v.idVariante} className="flex items-center gap-3 py-2 text-sm text-gray-200"><input type="checkbox" checked={seleccionadas.includes(v.idVariante)} onChange={(e)=>setSeleccionadas(e.target.checked?[...seleccionadas,v.idVariante]:seleccionadas.filter(id=>id!==v.idVariante))}/><span className="min-w-0 flex-1 truncate">{v.nombreVisible}</span><span className="text-xs text-gray-400">{listas.find(l=>l.idListaPrecio===v.listaEfectiva)?.nombre??'Sin lista'}</span></label>)}</div></Card></div>
}
